interface LevisAPI {
  getHomeDir: () => Promise<string>;
  getAppVersion: () => Promise<string>;
  clipboardRead: () => Promise<string>;
  clipboardReadImage: (projectPath: string) => Promise<string | null>;
  clipboardWrite: (text: string) => void;
  createDesktopShortcut: () => Promise<{ success: boolean; path?: string; dev?: boolean; error?: string; message?: string }>;
  mobileEnableTouch: (webContentsId: number) => Promise<boolean>;
  mobileDisableTouch: (webContentsId: number) => Promise<boolean>;
  mobileSetColorScheme: (webContentsId: number, scheme: 'dark' | 'light') => Promise<boolean>;
  mobileTouch: (webContentsId: number, type: 'touchStart' | 'touchMove' | 'touchEnd' | 'touchCancel', x: number, y: number) => void;
  minimize: () => void;
  maximize: () => void;
  close: () => void;
  hardReload: () => void;
  forceQuit: () => void;
  onWindowOsFocus: (cb: () => void) => () => void;
  onWindowOsBlur: (cb: () => void) => () => void;
  onConfirmQuit: (cb: () => void) => () => void;
  popout: (data: { type: string; url?: string; filePath?: string; projectPath?: string }) => Promise<any>;
  popoutPanel: (data: { panelType: 'terminal' | 'editor'; payload: any }) => Promise<{ panelId: string }>;
  closePopoutPanel: (panelId: string) => void;
  popoutRefresh: () => void;
  popoutNotifyCCDone: () => void;
  onPopoutLoad: (cb: (data: any) => void) => () => void;
  onPopoutRefresh: (cb: () => void) => () => void;
  onPopoutClosed: (cb: () => void) => () => void;
  onPopoutSendPrompt: (cb: (payload: { text: string; submit: boolean }) => void) => () => void;
  storeGet: (key: string) => Promise<any>;
  storeSet: (key: string, value: any) => Promise<void>;
  storeGetAll: () => Promise<any>;
  scanProjects: (path: string) => Promise<any[]>;
  getPinnedProjects: () => Promise<string[]>;
  togglePinProject: (projectPath: string) => Promise<boolean>;
  getProjectPrefs: (projectPath: string) => Promise<{ panelsSwapped?: boolean; workspaceLayout?: unknown; editorOpenFiles?: string[] }>;
  setProjectPref: (projectPath: string, key: string, value: any) => Promise<void>;
  gitStatus: (projectPath: string) => Promise<any>;
  gitPull: (projectPath: string) => Promise<any>;
  gitLog: (projectPath: string, count?: number) => Promise<any>;
  gitDiff: (projectPath: string) => Promise<string>;
  gitDiffStaged: (projectPath: string) => Promise<string>;
  gitCommit: (projectPath: string, message: string, push?: boolean) => Promise<{ success?: boolean; error?: string; commit?: any; pushError?: string }>;
  gitPush: (projectPath: string) => Promise<{ success?: boolean; error?: string }>;
  gitRevparse: (projectPath: string) => Promise<string>;
  gitResetHard: (projectPath: string, hash: string) => Promise<{ success?: boolean; error?: string }>;
  gitDiffRange: (projectPath: string, fromHash: string) => Promise<{ files: number; insertions: number; deletions: number } | { error: string }>;
  gitRecentFiles: (projectPath: string) => Promise<string[]>;
  captureRegion: (rect: { x: number; y: number; width: number; height: number }, savePath: string) => Promise<{ success?: boolean; path?: string; error?: string }>;
  captureCleanup: (tmpDir: string) => Promise<{ success?: boolean; error?: string }>;
  deleteProject: (projectPath: string) => Promise<{ success?: boolean; error?: string }>;
  renameProject: (oldPath: string, newName: string) => Promise<{ success?: boolean; path?: string; error?: string }>;
  duplicateProject: (sourcePath: string, newName: string) => Promise<{ success?: boolean; path?: string; error?: string }>;
  shellOpenPath: (targetPath: string) => Promise<{ success?: boolean; error?: string }>;
  openExternal: (url: string) => Promise<{ success?: boolean; error?: string }>;
  deleteFile: (filePath: string) => Promise<{ success?: boolean; error?: string }>;
  readDir: (dirPath: string) => Promise<Array<{ name: string; path: string; isDirectory: boolean }>>;
  dirStats: (dirPath: string) => Promise<{ files: number; size: number }>;
  fileStats: (filePath: string) => Promise<{ isDirectory?: boolean; files?: number; size: number } | null>;
  pathExists: (p: string) => Promise<boolean>;
  listFilesRecursive: (rootPath: string) => Promise<Array<{ path: string; rel: string; name: string }>>;
  projectAssetsHash: (rootDir: string) => Promise<string>;
  projectSearch: (rootPath: string, query: string, opts?: { caseSensitive?: boolean; regex?: boolean }) => Promise<Array<{ path: string; rel: string; line: number; col: number; preview: string }>>;
  projectReplace: (rootPath: string, query: string, replacement: string, opts?: { caseSensitive?: boolean; regex?: boolean; targetFiles?: string[] }) => Promise<{ count: number; error?: string }>;
  readFile: (filePath: string) => Promise<string | { error: string }>;
  writeFile: (filePath: string, content: string) => Promise<{ success?: boolean; error?: string }>;
  getLanguage: (filePath: string) => Promise<string>;
  createDir: (dirPath: string) => Promise<{ success?: boolean; error?: string }>;
  openFolderDialog: () => Promise<string | null>;
  openFileDialog: (multi?: boolean) => Promise<string[] | null>;
  createPty: (cwd: string) => Promise<string>;
  writePty: (id: string, data: string) => void;
  resizePty: (id: string, cols: number, rows: number) => void;
  killPty: (id: string) => void;
  onPtyData: (callback: (id: string, data: string) => void) => () => void;
  onPtyExit: (callback: (id: string) => void) => () => void;
  generateClaudeMd: (projectPath: string) => Promise<any>;
  scaffoldProject: (name: string, targetDir: string, template?: string) => Promise<any>;
  usageScan: () => Promise<any>;
  usageAccount: () => Promise<any>;
  usageRateLimits: () => Promise<any>;
  onUsageUpdated: (cb: () => void) => () => void;
  billingGetHookStatus: () => Promise<{
    scriptInstalled: boolean;
    ourHookActive: boolean;
    hasOtherStatusline: boolean;
    otherStatuslineCmd: string | null;
    dumpAgeMs: number | null;
    wrapperActive: boolean;
  }>;
  billingInstallHook: (opts?: { wrapExisting?: boolean }) => Promise<{ success: boolean; error?: string; status?: any }>;
  billingUninstallHook: () => Promise<{ success: boolean; restored?: boolean; error?: string; status?: any }>;
  // CC onboarding
  ccDetect: () => Promise<{ installed: boolean; version: string | null; path: string | null; source: 'native' | 'npm' | 'path' | null }>;
  ccInstallCommand: () => Promise<{ cmd: string; docsUrl: string }>;
  // Auto-update
  updateCheck: () => Promise<{ success?: boolean; error?: string }>;
  updateDownload: () => Promise<{ success?: boolean; error?: string }>;
  updateInstall: () => Promise<{ success?: boolean }>;
  onUpdateStatus: (cb: (data: { status: 'checking' | 'available' | 'not-available' | 'downloading' | 'downloaded' | 'error'; version?: string; percent?: number; transferred?: number; total?: number; bytesPerSecond?: number; message?: string; releaseNotes?: string | null; releaseDate?: string }) => void) => () => void;
}

declare const levis: LevisAPI;
declare function t(key: string, params?: Record<string, string | number>): string;
declare function setLocale(loc: 'en' | 'cs'): void;
declare function getLocale(): 'en' | 'cs';
declare function applyI18nDom(root: Document | HTMLElement): void;
declare function initI18n(): Promise<void>;
declare function applyTheme(theme: string): void;

interface Window {
  renderHub: (container: HTMLElement, onOpenProject: (project: any) => void) => Promise<void>;
  createTerminal: (container: HTMLElement, cwd: string, projectName: string) => Promise<any>;
  createBrowser: (container: HTMLElement, defaultUrl?: string, projectPath?: string, injectedHost?: unknown) => any;
  createWorkspace: (projectPath: string, projectName: string) => Promise<any>;
  createFileTree: (container: HTMLElement, rootPath: string, onFileOpen: (path: string) => void) => any;
  createEditor: (container: HTMLElement) => Promise<any>;
  createDiffViewer: (container: HTMLElement) => any;
  createInspector: () => any;
  showGralPicker: (parent: HTMLElement, sablonyPath: string) => Promise<string | null>;
  createGralAudit: (container: HTMLElement, projectPath: string) => any;
  createTokenViewer: (container: HTMLElement, projectPath: string) => any;
  showToast: (message: string, type?: 'info' | 'success' | 'warning' | 'error') => void;
  commandPalette: { show: () => void; hide: () => void; registerCommand: (cmd: any) => void };
}
